
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './redux/provider'
import Authprovider from './authProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shopping Unlimited',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Authprovider >
          <Providers>
            {children}
          </Providers>
        </Authprovider>
      </body>
    </html>
  )
}
